export const GET_TOKEN = 'GET_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';

export const GET_LOCAL_FILES_SUCCESSFUL = "GET_LOCAL_FILES_SUCCESSFUL";
export const GET_LOCAL_FILES_FAILED = "GET_LOCAL_FILES_FAILED";
export const TRY_GET_LOCAL_FILES = "TRY_GET_LOCAL_FILES";
export const GET_FILES = "GET_FILE";
export const SAVE_FILES = "SAVE_FILE";