export const GET_TOKEN = 'GET_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';

export const SAVE_SENTENCES = "SAVE_SENTENCES";
export const REMOVE_SENTENCES = "REMOVE_SENTENCES";
export const ADD_SENTENCE = "ADD_SENTENCE";
export const GET_LOCAL_FILES_FAILED = "GET_LOCAL_FILES_FAILED";
export const TRY_GET_LOCAL_FILES = "TRY_GET_LOCAL_FILES";
export const GET_FILES = "GET_FILE";
export const SAVE_FILES = "SAVE_FILE";
